# Generated by Django 4.2.3 on 2023-10-8 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="description",
        ),
        migrations.AddField(
            model_name="recipe",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                choices=[
                    ("breakfast", "Desayuno"),
                    ("lunch", "Almuerzo"),
                    ("snack", "Merienda"),
                    ("dinner", "Cena"),
                ],
                null=True,
                to="blog.recipe",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("normal", "Normal"), ("hard", "Hard")],
                default="easy",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]