# Generated by Django 4.2.3 on 2023-10-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_category_alter_recipe_categories"),
        ("landing", "0002_customuser_avatar_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="favorites", to="blog.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="liked_recipes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="liked_recipes", to="blog.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="recipes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="recipes", to="blog.recipe"
            ),
        ),
    ]