# Generated by Django 4.2.3 on 2023-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_category_alter_recipe_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="conversation",
        ),
        migrations.AddField(
            model_name="conversation",
            name="messages",
            field=models.ManyToManyField(blank=True, to="blog.message"),
        ),
    ]